### ISSUE TITLE
Add a "knowledge base" tab near the discussion tab

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#377] opened 2018-09-21 16:04 UTC
Add a "knowledge base" tab near the discussion tab so people can easily access it

**Comment by kanalumaddela** [comment] 2018-09-21 17:38
I say it should be on the right side are next to the support button. Dunno if it should show no matter whether a user owns it or not.

**Comment by ExtReMLapin** [comment] 2018-09-21 17:43
this idea is just to make it more visible

**Comment by kanalumaddela** [comment] 2018-09-21 18:08
The sidebar is definitely more noticeable than the new sub nav to users

**Comment by Marcuzz** [comment] 2018-09-21 19:07
Duplicate of your own issue, #282

**Closed by Marcuzz** 2018-09-21 19:07 UTC
