### ISSUE TITLE
Addon "in submissions queue" even though it should have been active

### ISSUE THREAD

**Issue by CommanderNZ** [gmodstore/gmodstore-issues#173] opened 2018-08-07 11:36 UTC
Underdone RPG https://beta.gmodstore.com/market/view/750
Is missing from https://beta.gmodstore.com/dashboard/addons
When viewing the edit page for it, it claims it is "Awaiting approval"

![image](https://user-images.githubusercontent.com/10164520/43773683-a1c2f0a4-9a9a-11e8-91e2-fd780147f3df.png)
![image](https://user-images.githubusercontent.com/10164520/43773697-ade19ca0-9a9a-11e8-8d85-fe309b97ab96.png)

**Comment by ExtReMLapin** [comment] 2018-08-07 11:39
So i guess the issue is it's  "Awaiting for approval"

**Comment by CommanderNZ** [comment] 2018-08-07 11:42
Well, there would be two issues then really.
1. No list shown for "Awaiting for approval"
2. Why would an approved addon suddenly be made into this status?

**Comment by Marcuzz** [comment] 2018-08-07 11:49
1. Has been fixed now

2. This has to be investigated further as I can't think of an obvious cause yet. Seems to be an edge case since your addon is the only known addon to have this happen to it so far

**Comment by Marcuzz** [comment] 2018-08-07 21:03
This has been fixed. Will be fixed on the beta site once I get to re-import the database. Likely tomorrow as it's getting late here.

**Closed by Marcuzz** 2018-08-07 21:03 UTC
