### ISSUE TITLE
Wishlist images not showing.

### ISSUE THREAD

**Issue by Livaco** [gmodstore/gmodstore-issues#432] opened 2018-09-30 20:18 UTC
![image](https://user-images.githubusercontent.com/15859232/46262235-6036c080-c4f6-11e8-8810-6361abc83c69.png)

Ment to be the BLogs banner.

**Comment by ExtReMLapin** [comment] 2018-10-01 08:41
duplicate of #255 (closed tho)

**Comment by Marcuzz** [comment] 2018-10-01 08:42
I don't really think this is an issue anymore. @kanalumaddela can see it just fine

**Closed by Marcuzz** 2018-10-01 08:42 UTC

**Comment by ExtReMLapin** [comment] 2018-10-01 08:43
it is still an Issue, I can reproduce it

**Comment by ExtReMLapin** [comment] 2018-10-01 08:43
reeeee

**Comment by Marcuzz** [comment] 2018-10-01 09:33
It's probably because the image you're trying to look at has not been updated since last time it was broken.

**Comment by Livaco** [comment] 2018-10-03 10:11
![image](https://user-images.githubusercontent.com/15859232/46404421-0227fa00-c6fd-11e8-862c-c563f19e89f2.png)
It seems the _small in the image path is what is causing the issue. I removed it and worked fine.
![image](https://user-images.githubusercontent.com/15859232/46404438-166bf700-c6fd-11e8-9ee6-9b5725525527.png)

**Comment by Marcuzz** [comment] 2018-10-03 14:44
That's because Billy has not updated his addon image since we fixed it last time. The issue last time is it wasn't generating a _small. Billy has to update his banners and it'll work fine from then on.
