### ISSUE TITLE
i have 434 pages of shit logs

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#418] opened 2018-09-26 16:53 UTC
from https://www.gmodstore.com/users/Lapin/events?page=1

to 

https://www.gmodstore.com/users/Lapin/events?page=433

![](https://i.imgur.com/a9eWM8l.png)

**Comment by ExtReMLapin** [comment] 2018-09-26 16:54
was caused by #384

**Comment by J0sh0nat0r** [comment] 2018-09-26 17:09
Duplicate of #408

**Closed by J0sh0nat0r** 2018-09-26 17:09 UTC
Labels: bug
