### ISSUE TITLE
500 when trying to edit knowledge base article

### ISSUE THREAD

**Issue by ExtReMLapin** [gmodstore/gmodstore-issues#283] opened 2018-09-17 13:32 UTC
https://www.gmodstore.com/help/addon/4858/how-to-correctly-add-houses-apartments/how-to-deal-with-no-room-to-place-the-front-door-panel

here

**Comment by Marcuzz** [comment] 2018-09-19 14:35
Duplicate of #245

**Comment by ExtReMLapin** [comment] 2018-09-19 14:36
OOPS

**Closed** 2018-09-19 14:35 UTC
Labels: bug, duplicate, medium priority
