### ISSUE TITLE
Revokes didn't carry over

### ISSUE THREAD

**Issue by OwjoTheGreat** [gmodstore/gmodstore-issues#101] opened 2018-08-02 14:27 UTC
As stated in the title, script revokes didn't transfer.

(Submitted on behalf of Commander)

**Comment by ExtReMLapin** [comment] 2018-08-02 14:30
fucking high priority shit

**Comment by OwjoTheGreat** [comment] 2018-08-02 14:30
Was posted by request, don't hate me please daddy Lapin.

**Comment by ExtReMLapin** [comment] 2018-08-02 14:32
it wasn't sarcasm

**Comment by Marcuzz** [comment] 2018-08-02 14:59
Are these only for manual revokes? Because 6488 revokes were actually ported

**Comment by ExtReMLapin** [comment] 2018-08-02 15:03
I just checked

worked on my side

![](https://i.imgur.com/H1DLr87.png)

**Comment by Marcuzz** [comment] 2018-08-02 15:13
I just confirmed it with the v2 database this was ported from and there is actually only one missing revoke, which was likely one that was missing a user_id from the early days of ScriptFodder v1

There were 6489 revokes in v2, and there are 6488 in v3

**Comment by WilliamVenner** [comment] 2018-08-02 15:25
probably just commander being an old man and not realising that the database migration is not up to date

**Comment by CommanderNZ** [comment] 2018-08-02 15:35
Well you are wrong.
https://cdn.discordapp.com/attachments/473226192988930068/474599708413657119/Screenshot_20180803-032937_Samsung_Internet.jpg
Bizzy and Heavy Bob don't own it, it was manually assigned then revoked.

**Comment by ExtReMLapin** [comment] 2018-08-02 15:43
i got 500 on heavy bob , can't check shit

**Comment by Marcuzz** [comment] 2018-08-02 16:08
Nope, I was right. That purchases list was just not displaying the right status of the purchase. Fixed in next deployment.

**Closed by Marcuzz** 2018-08-02 16:08 UTC
Labels: can't replicate
