### ISSUE TITLE
"Purchase Statistics" "Total spent on addons" amount is wrong and not formatted as currency

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#232] opened 2018-09-16 11:58 UTC
![image](https://user-images.githubusercontent.com/14863743/45596204-35098880-b9b0-11e8-902c-dbed1b278eb7.png)

https://beta.gmodstore.com/users/76561198040894045/purchases

**Comment by Marcuzz** [comment] 2018-09-16 12:04
Duplicate of #227

**Closed by Marcuzz** 2018-09-16 12:04 UTC
