### ISSUE TITLE
Forums sorting?

### ISSUE THREAD

**Issue by Jpofin** [gmodstore/gmodstore-issues#422] opened 2018-09-27 12:28 UTC
The threads (atleast in the hire me section) seem a bit unsorted for me.

Correct me but this isn't sorted by last posted, neither by creation date.

http://i.epvpimg.com/62hjeab.png

how is this sorted?

**Comment by Marcuzz** [comment] 2018-09-27 13:14
Duplicate of #236

**Closed by Marcuzz** 2018-09-27 13:14 UTC
