### ISSUE TITLE
Team shows denied addons

### ISSUE THREAD

**Issue by DrPepperG** [gmodstore/gmodstore-issues#311] opened 2018-09-18 00:34 UTC
The team is showing the denied addons and while they are all denied the creator still has the content creator rank.

![](https://i.ambigboy.xyz/Ga9eM.png)

![](https://i.ambigboy.xyz/h957X.png)

**Comment by Marcuzz** [comment] 2018-09-19 20:10
Duplicate of #244

**Closed by Marcuzz** 2018-09-19 20:10 UTC
Labels: bug, medium priority
