### ISSUE TITLE
Character minimum and anchor

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#122] opened 2018-08-02 21:52 UTC
At https://beta.gmodstore.com/community/threads/6062/page/1#post-41557 : 
- The anchor post doesn't work, I'm at the top of the page while I clicked on my post in the "Latest posts"part
- I am able to write a post with only a space. Give a limit as you made in the support ticket currently, like you are forced to put at least 3 characters to post something....

**Comment by Marcuzz** [comment] 2018-08-03 12:23
Anchor is duplicate of #27

**Comment by J0sh0nat0r** [comment] 2018-08-05 01:33
Thanks for the report! The second issue has been fixed in the next release.

**Closed by J0sh0nat0r** 2018-08-05 01:33 UTC
Labels: bug
